services:
  backend:
    build:
      context: ./Backend
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./Frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    env_file:
      - ./Frontend/.env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
